### ISSUE TITLE
Feature Request : Live Refresh Via inotify or similar

### ISSUE THREAD

**Issue by benyanke** [glipari/ptask#11]
Thanks for this excellent frontend for taskwarrior!

It would be awesome to use something like inotify to live-refresh on file change, avoiding the need (in most cases) for a manual refresh. Given the very small number of files in `~/.task` typically, I imagine this would incur minimal overhead.

**Comment by glipari** [comment]
Sorry, I think you are commenting on the wrong project. The Ptask library is definitely not a front-end for taskwarrior! And there is no .task file. SO, I have no idea what you are talking about.

**Comment by benyanke** [comment]
Whoops, I mixed up my links! My apologies. 

This is what I thought I was looking for:
https://wpitchoune.net/ptask/
